//
//  OhioBrandData.m
//  LiqorStoreLocator
//
//  Created by Akash Aggarwal on 7/30/14.
//
//

#import "OhioBrandData.h"


@implementation OhioBrandData

@dynamic agencynumber;
@dynamic b_retailprice_1;
@dynamic b_retailprice_2;
@dynamic b_retailprice_3;
@dynamic b_retailprice_4;
@dynamic b_retailprice_5;
@dynamic b_retailprice_6;
@dynamic b_retailprice_7;
@dynamic b_retailprice_8;
@dynamic b_retailprice_9;
@dynamic b_retailprice_10;
@dynamic b_retailprice_11;
@dynamic b_retailprice_12;
@dynamic b_wholesaleprice_1;
@dynamic b_wholesaleprice_2;
@dynamic b_wholesaleprice_3;
@dynamic b_wholesaleprice_4;
@dynamic b_wholesaleprice_5;
@dynamic b_wholesaleprice_6;
@dynamic b_wholesaleprice_7;
@dynamic b_wholesaleprice_8;
@dynamic b_wholesaleprice_9;
@dynamic b_wholesaleprice_10;
@dynamic b_wholesaleprice_11;
@dynamic b_wholesaleprice_12;
@dynamic brandcode;
@dynamic brandname;
@dynamic county;
@dynamic createdAt;
@dynamic d_retailprice_1;
@dynamic d_retailprice_2;
@dynamic d_retailprice_3;
@dynamic d_retailprice_4;
@dynamic d_retailprice_5;
@dynamic d_retailprice_6;
@dynamic d_retailprice_7;
@dynamic d_retailprice_8;
@dynamic d_retailprice_9;
@dynamic d_retailprice_10;
@dynamic d_retailprice_11;
@dynamic d_retailprice_12;
@dynamic d_wholesaleprice_1;
@dynamic d_wholesaleprice_2;
@dynamic d_wholesaleprice_3;
@dynamic d_wholesaleprice_4;
@dynamic d_wholesaleprice_5;
@dynamic d_wholesaleprice_6;
@dynamic d_wholesaleprice_7;
@dynamic d_wholesaleprice_8;
@dynamic d_wholesaleprice_9;
@dynamic d_wholesaleprice_10;
@dynamic d_wholesaleprice_11;
@dynamic d_wholesaleprice_12;
@dynamic e_retailprice_1;
@dynamic e_retailprice_2;
@dynamic e_retailprice_3;
@dynamic e_retailprice_4;
@dynamic e_retailprice_5;
@dynamic e_retailprice_6;
@dynamic e_retailprice_7;
@dynamic e_retailprice_8;
@dynamic e_retailprice_9;
@dynamic e_retailprice_10;
@dynamic e_retailprice_11;
@dynamic e_retailprice_12;
@dynamic e_wholesaleprice_1;
@dynamic e_wholesaleprice_2;
@dynamic e_wholesaleprice_3;
@dynamic e_wholesaleprice_4;
@dynamic e_wholesaleprice_5;
@dynamic e_wholesaleprice_6;
@dynamic e_wholesaleprice_7;
@dynamic e_wholesaleprice_8;
@dynamic e_wholesaleprice_9;
@dynamic e_wholesaleprice_10;
@dynamic e_wholesaleprice_11;
@dynamic e_wholesaleprice_12;
@dynamic l_retailprice_1;
@dynamic l_retailprice_2;
@dynamic l_retailprice_3;
@dynamic l_retailprice_4;
@dynamic l_retailprice_5;
@dynamic l_retailprice_6;
@dynamic l_retailprice_7;
@dynamic l_retailprice_8;
@dynamic l_retailprice_9;
@dynamic l_retailprice_10;
@dynamic l_retailprice_11;
@dynamic l_retailprice_12;
@dynamic l_wholesaleprice_1;
@dynamic l_wholesaleprice_2;
@dynamic l_wholesaleprice_3;
@dynamic l_wholesaleprice_4;
@dynamic l_wholesaleprice_5;
@dynamic l_wholesaleprice_6;
@dynamic l_wholesaleprice_7;
@dynamic l_wholesaleprice_8;
@dynamic l_wholesaleprice_9;
@dynamic l_wholesaleprice_10;
@dynamic l_wholesaleprice_11;
@dynamic l_wholesaleprice_12;
@dynamic m_retailprice_1;
@dynamic m_retailprice_2;
@dynamic m_retailprice_3;
@dynamic m_retailprice_4;
@dynamic m_retailprice_5;
@dynamic m_retailprice_6;
@dynamic m_retailprice_7;
@dynamic m_retailprice_8;
@dynamic m_retailprice_9;
@dynamic m_retailprice_10;
@dynamic m_retailprice_11;
@dynamic m_retailprice_12;
@dynamic m_wholesaleprice_1;
@dynamic m_wholesaleprice_2;
@dynamic m_wholesaleprice_3;
@dynamic m_wholesaleprice_4;
@dynamic m_wholesaleprice_5;
@dynamic m_wholesaleprice_6;
@dynamic m_wholesaleprice_7;
@dynamic m_wholesaleprice_8;
@dynamic m_wholesaleprice_9;
@dynamic m_wholesaleprice_10;
@dynamic m_wholesaleprice_11;
@dynamic m_wholesaleprice_12;
@dynamic objectId;
@dynamic syncStatus;
@dynamic taxrate;
@dynamic updatedAt;

@end
